### ISSUE TITLE
Erreur PHP 

### ISSUE THREAD

**Issue by thorgal333** [ThomasEcalle/projet_poivey_test#1]
J'ai essayé ce programme et j'ai l'erreur suivante:
Parse error: syntax error, unexpected '++' (T_INC), expecting ';' in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\ExoTableau\Exo1.php on line 24

Pourriez-vous corriger ce problème rapidement?

**Comment by ThomasEcalle** [comment]
Erreur corrigée , merci !
